//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactorySchematic) DeepCopyInto(out *FactorySchematic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactorySchematic.
func (in *FactorySchematic) DeepCopy() *FactorySchematic {
	if in == nil {
		return nil
	}
	out := new(FactorySchematic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FactorySchematic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactorySchematicList) DeepCopyInto(out *FactorySchematicList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FactorySchematic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactorySchematicList.
func (in *FactorySchematicList) DeepCopy() *FactorySchematicList {
	if in == nil {
		return nil
	}
	out := new(FactorySchematicList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FactorySchematicList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactorySchematicObservation) DeepCopyInto(out *FactorySchematicObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactorySchematicObservation.
func (in *FactorySchematicObservation) DeepCopy() *FactorySchematicObservation {
	if in == nil {
		return nil
	}
	out := new(FactorySchematicObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactorySchematicParameters) DeepCopyInto(out *FactorySchematicParameters) {
	*out = *in
	if in.Schematic != nil {
		in, out := &in.Schematic, &out.Schematic
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactorySchematicParameters.
func (in *FactorySchematicParameters) DeepCopy() *FactorySchematicParameters {
	if in == nil {
		return nil
	}
	out := new(FactorySchematicParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactorySchematicSpec) DeepCopyInto(out *FactorySchematicSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactorySchematicSpec.
func (in *FactorySchematicSpec) DeepCopy() *FactorySchematicSpec {
	if in == nil {
		return nil
	}
	out := new(FactorySchematicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FactorySchematicStatus) DeepCopyInto(out *FactorySchematicStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FactorySchematicStatus.
func (in *FactorySchematicStatus) DeepCopy() *FactorySchematicStatus {
	if in == nil {
		return nil
	}
	out := new(FactorySchematicStatus)
	in.DeepCopyInto(out)
	return out
}
