# Step 2: Configuration - Generate Talos machine configuration using Secrets
apiVersion: machine.talos.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: single-node-controlplane-config
spec:
  forProvider:
    # Cluster settings
    clusterName: single-node-cluster
    clusterEndpoint: https://192.168.120.83:6443
    
    # Machine type for control plane node
    machineType: controlplane
    
    # Reference to the machine secrets
    machineSecretsRef:
      name: single-node-secrets
      
    # Configuration patches for single-node setup
    configPatches:
      - |
        cluster:
          allowSchedulingOnControlPlanes: true
          network:
            cni:
              name: flannel
        machine:
          network:
            hostname: "single-node"
            interfaces:
              - interface: eth0
                dhcp: true
          kubelet:
            # Allow single-node cluster
            registerWithTaints: []
  
  providerConfigRef:
    name: default