# Step 2: Secrets - Generate cluster secrets and certificates  
# This creates all the PKI materials needed for the Talos cluster
apiVersion: machine.talos.crossplane.io/v1alpha1
kind: Secrets
metadata:
  name: single-node-secrets
spec:
  forProvider:
    # Talos version for compatibility
    talosVersion: "v1.8"
  
  # Use default provider config
  providerConfigRef:
    name: default
    
  # Write connection secrets containing the certificates
  writeConnectionSecretToRef:
    name: single-node-talos-secrets
    namespace: default