# Step 6: ClusterKubeconfig - Retrieve the kubeconfig for the cluster
apiVersion: cluster.talos.crossplane.io/v1alpha1
kind: Kubeconfig
metadata:
  name: single-node-kubeconfig
spec:
  forProvider:
    # Control plane node and endpoint
    node: "192.168.120.82"
    endpoint: "192.168.120.82"
    
    # Client configuration for Talos API
    clientConfiguration:
      caCertificate: |
        -----BEGIN CERTIFICATE-----
        MIIBPjCB8aADAgECAhBkMCINgMoL15DyhL1lgXJgMAUGAytlcDAQMQ4wDAYDVQQK
        EwV0YWxvczAeFw0yNTA5MDkxODAzMzhaFw0zNTA5MDcxODAzMzhaMBAxDjAMBgNV
        BAoTBXRhbG9zMCowBQYDK2VwAyEA9r2CcPVULVvXG01FwKeIEigaJr9YR6gSXzJe
        llib2UajYTBfMA4GA1UdDwEB/wQEAwIChDAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
        KwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU/ujzE8hh7saxPy0c
        ObLtubXhnxIwBQYDK2VwA0EAWnwxrZZXvOXTFpiD7IGYikpROKzNsuQEQd+4ZyOx
        2o+ir6urtSDYFVYyVDKdvJpAzqjgDgYhYiwiu/oc5oWeAw==
        -----END CERTIFICATE-----
      clientCertificate: |
        -----BEGIN CERTIFICATE-----
        MIIBPjCB8aADAgECAhBkMCINgMoL15DyhL1lgXJgMAUGAytlcDAQMQ4wDAYDVQQK
        EwV0YWxvczAeFw0yNTA5MDkxODAzMzhaFw0zNTA5MDcxODAzMzhaMBAxDjAMBgNV
        BAoTBXRhbG9zMCowBQYDK2VwAyEA9r2CcPVULVvXG01FwKeIEigaJr9YR6gSXzJe
        llib2UajYTBfMA4GA1UdDwEB/wQEAwIChDAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
        KwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU/ujzE8hh7saxPy0c
        ObLtubXhnxIwBQYDK2VwA0EAWnwxrZZXvOXTFpiD7IGYikpROKzNsuQEQd+4ZyOx
        2o+ir6urtSDYFVYyVDKdvJpAzqjgDgYhYiwiu/oc5oWeAw==
        -----END CERTIFICATE-----
      clientKey: |
        -----BEGIN ED25519 PRIVATE KEY-----
        MC4CAQAwBQYDK2VwBCIEIDcTLHEOE70yzzXAjgeFZnGcG9nKjXbsUqX0mkxJI4OK
        -----END ED25519 PRIVATE KEY-----
  
  # The kubeconfig will be written to a Kubernetes secret
  writeConnectionSecretToRef:
    name: single-node-kubeconfig-secret
    namespace: default
  
  providerConfigRef:
    name: default